### ISSUE TITLE
Invalid values for export

### ISSUE THREAD

**Issue by scoughlin1** [splunk/cloud-datamodel-security-research#4]
In default.meta under [views] stanza:
export = system, apps

Splunk indicate this is invalid.

**Comment by rvaldez617** [comment]
Thanks for the report. There are no views included, so I have removed the invalid entry. We will be making some other updates, so I have not created a new build. You can simply remove the views stanza or do a pull to get the update

**Comment by rvaldez617** [comment]
Updated to address
