### ISSUE TITLE
Fields for containerized apps/services?

### ISSUE THREAD

**Issue by wryanthomas** [splunk/cloud-datamodel-security-research#5]
Thanks for this! The 'compute' section seems designed for VMs (the docs suggest it too).  Have you thought about how containerized apps/services can fit in to this model? Have you seen anyone extend this model to support containerized apps/service?

**Comment by rvaldez617** [comment]
Hey wranthomas! No problem! Hope you find it useful. We have not had a chance to dig into how we would map container-related info in here, but we recognize it's a need. I'm not aware of anybody else trying to extend the model for that yet either. We've done some early work with kubernetes data, but haven't hit it in earnest. Would be happy to discuss further, and would also be interested in the specific data sources you'd want to use to populate something like that. Shoot me an email at rvaldez@splunk.com if you'd like to discuss.
